language: java
jdk:
  - oraclejdk8
before_install:
  - export | grep SAUCE_
env:
  global:
    - SAUCE_USERNAME=sauce_examples
script: mvn clean test
addons:
  jwt:
    secure: "i4p7iSjXqXY1NbQhdw153pX1Gvu65DWWsLgsrw/wKjSJtdobDtPvpftgBpgLw9/jL/4GpEmpGq2GX1hlz8HqCxCTWI7yzg3wYuLA0gNPjciCueWcgQTOZRJI+J7rcdhArN8vKy5PQIkL32uXwGZLFn/iC5xzR69e9fwNbF+SwVFfBFlksEJ3qlkC7rlQXTR8LSNp2WPPuHHcE7dqUUJN590vJo+lwACGEMKmgSdJWBBCvBGJ24iPkPhTKD0IwiJgRLG9JAiOLSkTu9yVRKUaUq3hrdUQNVLmJevR/xK3BOrbaKdarLFa+ML6iNwKG9kmyvK7EchqDgzo20N2fFLlIJMHP1zOYtT/X6v9YKGgLRrc0ixny8hrabjL70IQAkjv0jdKJX3HiMTU0rmzpr3hRL9hldGvMfqA16R75YAhyG3ndK0jKxbWi04IvGIsMZuLm3Jbu83iJ+9AbNF/4D0Vyd0kJ1w1d/8PelIiR9K4n6K7ZjIz7BPeYb8mfJZZN/MiD7/Me4pFrDyUadM/T5zBg1xwLezQIvs535Ym4exdF9vHKwFHbSxbO+ydMfVAfWdDCgTe9INEcqB+A9OazezgLAaK0LPN/H625KqpHCNKvUBQTl0J/SK76PjZESyUNOdWmdQKIcqRFurKxcHVZjkYz1g+hCjmAjaXjHsCFll/Pq0="
